apiVersion: v1
kind: ConfigMap
metadata:
  name: pdsync-config
data:
  config.yaml: |
    slackSyncs:
    - name: team-awesome
      schedules:
      - name: Awesome-Primary
      - id: D34DB33F
      channel:
        name: awesome
      template: |-
        primary on-call: <@{{.AwesomePrimary}}> secondary on-call: <@{{.AwesomeSecondary}}>
      dryRun: false
